import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import getDictionary from '@/lib/dictionaries';
import ReduxProvider from '@/components/ReduxProvider';
import { locales } from '@/constants/common';

const inter = Inter({ subsets: ['latin'] });

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  const messages = await getDictionary(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxProvider>{children}</ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
